# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=200)),
                ('nome', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('datanascita', models.DateField(blank=True, default=None, null=True)),
                ('luogonascita', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ruolo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('foto', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('telefonogenitore', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('telefonogiocatore', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('altezza', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('sistemaideale', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('societaappertenenza', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('scadenzacontratto', models.DateField(blank=True, default=None, null=True)),
                ('agente', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ingaggio', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('datainserimento', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Piede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descpiede', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='giocatore',
            name='piede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Piede'),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
