# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thetalentscout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calciare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desccalciare', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desccategoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conduzione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descconduzione', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Controllo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desccontrollo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fisicita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descfisicita', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squadrain', models.CharField(max_length=200)),
                ('moduloin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('squadraout', models.CharField(max_length=50)),
                ('moduloout', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('risultato', models.CharField(max_length=20)),
                ('foto', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('datainserimento', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Categoria')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Giocatoregara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forza', models.BooleanField(default=False)),
                ('resistenza', models.BooleanField(default=False)),
                ('velocita', models.BooleanField(default=False)),
                ('rapidita', models.BooleanField(default=False)),
                ('agilita', models.BooleanField(default=False)),
                ('coordinazione', models.BooleanField(default=False)),
                ('personalita', models.BooleanField(default=False)),
                ('concentrazione', models.BooleanField(default=False)),
                ('temperamento', models.BooleanField(default=False)),
                ('aggressivita', models.BooleanField(default=False)),
                ('autocontrollo', models.BooleanField(default=False)),
                ('disponibilita', models.BooleanField(default=False)),
                ('assomiglia', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('datainserimento', models.DateField(default=django.utils.timezone.now)),
                ('calciare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Calciare')),
                ('conduzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Conduzione')),
                ('controllo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Controllo')),
                ('fisicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Fisicita')),
                ('gara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Gara')),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Giocatore')),
            ],
        ),
        migrations.CreateModel(
            name='Giocoditesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descgiocoditesta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marcatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descmarcatura', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recuperapalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrecuperapalla', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Smarcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descsmarcamento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descstruttura', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='giocatoregara',
            name='giocoditesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Giocoditesta'),
        ),
        migrations.AddField(
            model_name='giocatoregara',
            name='marcatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Marcatura'),
        ),
        migrations.AddField(
            model_name='giocatoregara',
            name='recuperapalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Recuperapalla'),
        ),
        migrations.AddField(
            model_name='giocatoregara',
            name='smarcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Smarcamento'),
        ),
        migrations.AddField(
            model_name='giocatoregara',
            name='struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Struttura'),
        ),
        migrations.AddField(
            model_name='giocatoregara',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
