# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0002_auto_20171005_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giudizio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descgiudizio', models.CharField(max_length=200)),
            ],
        ),
    ]
