# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0004_giocatoregara_giudizio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatoregara',
            name='giudizio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Giudizio'),
        ),
    ]
