# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0006_auto_20171017_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='foto',
            field=models.FileField(default=b'pic_folder/None/no-img.jpg', null=True, upload_to=b'images/'),
        ),
    ]
