# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0011_auto_20171019_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'thetalentscout/static/images/'),
        ),
    ]
