# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0012_auto_20171020_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'images/'),
        ),
    ]
