# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0013_auto_20171020_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin1',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin10',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin11',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin12',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin13',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin14',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin15',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin16',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin17',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin18',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin19',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin2',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin20',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin3',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin4',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin5',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin6',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin7',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin8',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoin9',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout1',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout10',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout11',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout12',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout13',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout14',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout15',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout16',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout17',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout18',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout19',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout2',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout20',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout3',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout4',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout5',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout6',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout7',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout8',
        ),
        migrations.RemoveField(
            model_name='gara',
            name='nominativoout9',
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein10',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein11',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein12',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein13',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein14',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein15',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein16',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein17',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein18',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein19',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein20',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein4',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein5',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein6',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein7',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein8',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein9',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout10',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout11',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout12',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout13',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout14',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout15',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout16',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout17',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout18',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout19',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout20',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout4',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout5',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout6',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout7',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout8',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout9',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein10',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein11',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein12',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein13',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein14',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein15',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein16',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein17',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein18',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein19',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein20',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein4',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein5',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein6',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein7',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein8',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein9',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout10',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout11',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout12',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout13',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout14',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout15',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout16',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout17',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout18',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout19',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout20',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout4',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout5',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout6',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout7',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout8',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout9',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
