# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import thetalentscout.models


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0016_gara_dataincontro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotogiocatoregara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default=None, null=True, upload_to=thetalentscout.models.salva_foto_giocatore_gara)),
            ],
        ),
        migrations.RemoveField(
            model_name='gara',
            name='foto',
        ),
        migrations.AddField(
            model_name='fotogiocatoregara',
            name='gara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Gara'),
        ),
        migrations.AddField(
            model_name='fotogiocatoregara',
            name='giocatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Giocatore'),
        ),
    ]
