# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thetalentscout', '0017_auto_20171121_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotogiocatoregara',
            name='gara',
        ),
        migrations.RemoveField(
            model_name='fotogiocatoregara',
            name='giocatore',
        ),
        migrations.AddField(
            model_name='fotogiocatoregara',
            name='giocatore_gara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Giocatoregara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotogiocatoregara',
            name='utente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
