# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0018_auto_20171121_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotogiocatoregara',
            name='giocatore_gara',
        ),
        migrations.AddField(
            model_name='fotogiocatoregara',
            name='gara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Gara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotogiocatoregara',
            name='giocatore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thetalentscout.Giocatore'),
            preserve_default=False,
        ),
    ]
