# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thetalentscout', '0019_auto_20171121_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='gara',
            name='cognomein21',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein22',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein23',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein24',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomein25',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout21',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout22',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout23',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout24',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='cognomeout25',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein21',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein22',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein23',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein24',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomein25',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout21',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout22',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout23',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout24',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='nomeout25',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gara',
            name='tipo',
            field=models.CharField(default=b'U', max_length=1),
        ),
        migrations.AlterField(
            model_name='calciare',
            name='desccalciare',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='desccategoria',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='conduzione',
            name='descconduzione',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='controllo',
            name='desccontrollo',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='fisicita',
            name='descfisicita',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='gara',
            name='risultato',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='gara',
            name='squadrain',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='gara',
            name='squadraout',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='cognome',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='datanascita',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='giocoditesta',
            name='descgiocoditesta',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='giudizio',
            name='descgiudizio',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='marcatura',
            name='descmarcatura',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='piede',
            name='descpiede',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='recuperapalla',
            name='descrecuperapalla',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='smarcamento',
            name='descsmarcamento',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='struttura',
            name='descstruttura',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
